vpc:
  - name: 'vpc_region'
    CidrBlock: '10.0.0.0/16'
    EnableDnsHostnames: true

    region: 'ap-nottheast-1'

subnet:
  - name: 'public_subnet'
    CidrBlock: '10.0.1.0/24'
    AvailabilityZone: 'ap-northeast-1a'

  - name: 'private_subnet'
    CidrBlock: '10.0.2.0/24'
    AvailabilityZone: 'ap-northeast-1a'

internet_gateway:
  - name: 'gateway'

route_table:
  - name: 'public_rt'

route:
  - DestinationCidrBlock: '0.0.0.0/0'

security_group:
  - GroupName: 'web_server_sg'
    Description: 'A security group for public VPC'
    IpPermissions:
      # for ssh
      - IpProtocol: 'tcp'
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      # for web server
      - type: 'http'
        IpProtocol: 'tcp'
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'
      - type: 'costomized tcp'
        IpProtocol: 'tcp'
        FromPort: 8080
        ToPort: 8080
        CidrIp: '0.0.0.0/0'
      # for ping
      - IpProtocol: 'icmp'
        FromPort: -1
        ToPort: -1
        CidrIp: '0.0.0.0/0'
        CidrIpv6: '::/0'
  - GroupName: 'db_sg'
    Description: 'A security group for private VPC'
    IpPermissions:
      - IpProtocol: 'tcp'
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      # for DB
      - IpProtocol: 'tcp'
        FromPort: 3306
        ToPort: 3306
        CidrIp: '0.0.0.0/0'
        CidrIpv6: '::/0'
      # for ping
      - IpProtocol: 'icmp'
        FromPort: -1
        ToPort: -1
        CidrIp: '0.0.0.0/0'
        CidrIpv6: '::/0'

key:
  - key_name: 'web_server_ec2_key'
    save_dir_path: '/tmp'
