vpc:
  - name: 'vpc_region'
    CidrBlock: '10.0.0.0/16'
    EnableDnsHostnames: true

    region: 'ap-nottheast-1'

subnet:
  - name: 'public_subnet'
    CidrBlock: '10.0.1.0/24'
    AvailabilityZone: 'ap-northeast-1a'

  - name: 'private_subnet'
    CidrBlock: '10.0.2.0/24'
    AvailabilityZone: 'ap-northeast-1a'

internet_gateway:
  - name: 'gateway'

route_table:
  - name: 'public_rt'

route:
  - DestinationCidrBlock: '0.0.0.0/0'

sequrity_group:
  - name: 'public_sg'
    inbound:
      - type: 'ssh'
        protocol: 'tcp'
        port: 22
        source: '0.0.0.0/0'
      - type: 'http'
        protocol: 'tcp'
        port: 80
        source: '0.0.0.0/0'
      - type: 'costomized tcp'
        protocol: 'tcp'
        port: 8080
        source: '0.0.0.0/0'
      - type: 'All ICMP-IPv4'
        protocol: 'icmp'
        port: '0 - 65535'
        source: '::/0'
  - name: 'private_sg'
    inbound:
      - type: 'ssh'
        protocol: 'tcp'
        port: 22
        source: '0.0.0.0/0'
      - type: 'MYSQL/Aurora'
        protocol: 'tcp'
        port: 3306
        source: '0.0.0.0/0, ::/0'
      - type: 'All ICMP-IPv4'
        protocol: 'icmp'
        port: '0 - 65535'
        source: '::/0'

nat:
  - name: 'public_nat'
  - attach: 'public_vpc'

main_route_table:
  - attach: 'public_nat'
